import {
  Add01Icon,
  ArrowLeft01Icon,
  Cancel01Icon,
  DashboardCircleIcon,
  DiscoverCircleIcon,
  Edit01Icon,
  Home01Icon,
  LogoutIcon,
  Notification01Icon,
  SearchIcon,
  Telescope01Icon,
  Tick02Icon,
  User03Icon,
  UserAdd01Icon,
  UserIcon,
  X,
} from "@hugeicons/core-free-icons";
import type { Hugeicon } from "@/util/hugeicons";

export const ICON_MAP = {
  nav: {
    browse: DiscoverCircleIcon,
    dashboard: DashboardCircleIcon,
    queries: SearchIcon,
    admin: Telescope01Icon,
    users: UserIcon,
    clubs: DiscoverCircleIcon,
    joinRequests: User03Icon,
    dashboard: Home01Icon,
    back: ArrowLeft01Icon,
  },
  actions: {
    edit: Edit01Icon,
    reset: Cancel01Icon,
    approve: Tick02Icon,
    reject: Cancel01Icon,
    delete: Cancel01Icon,
    admin: UserIcon,
    status: Telescope01Icon,
    create: Add01Icon,
    join: UserAdd01Icon,
    leave: LogoutIcon,
  },
  status: {
    success: Tick02Icon,
    error: Cancel01Icon,
    empty: X,
    pending: Notification01Icon,
  },
  user: {
    profile: User03Icon,
    logout: LogoutIcon,
  },
  misc: {
    search: SearchIcon,
    close: X,
    logo: Telescope01Icon,
    feed: Notification01Icon,
  },
} as const satisfies Record<string, Record<string, Hugeicon>>;
