import {
  AdventureIcon,
  BicycleIcon,
  BookOpenIcon,
  BriefcaseIcon,
  CameraIcon,
  Camera01Icon,
  Chess01Icon,
  ChessKingIcon,
  ComputerTerminalIcon,
  CookBookIcon,
  Dumbbell01Icon,
  Film01Icon,
  FootballIcon,
  GameController01Icon,
  GlobeIcon,
  Knowledge01Icon,
  LaurelWreath01Icon,
  Leaf01Icon,
  MaskTheaterIcon,
  MegaphoneIcon,
  Mortarboard01Icon,
  MusicNote02Icon,
  PaintBoardIcon,
  SparklesIcon,
  StarIcon,
  SuperMarioIcon,
  SwimmingIcon,
  TennisRacketIcon,
  TestTube01Icon,
  TreeIcon,
  VolleyballIcon,
} from "@hugeicons/core-free-icons";
import type { Hugeicon } from "@/util/hugeicons";

export const CLUB_COLOR_HEX = {
  BLUE: "#5C8FC4",
  BLACK: "#72737A",
  RED: "#C27070",
  GREEN: "#4D9068",
  AMBER: "#C4923A",
  ORANGE: "#C47545",
  YELLOW: "#C4A740",
  CYAN: "#4498B0",
  PINK: "#C06888",
  PURPLE: "#836AB0",
  SLATE: "#6A7E94",
  TEAL: "#448A8A",
  INDIGO: "#6470AA",
  ROSE: "#AA6878",
} as const;

export type ClubColor = keyof typeof CLUB_COLOR_HEX;

export const ALLOWED_ICON_MAP = {
  ADVENTURE: AdventureIcon,
  AI_SPARKLES: SparklesIcon,
  BICYCLE: BicycleIcon,
  BOOK_OPEN: BookOpenIcon,
  BRIEFCASE: BriefcaseIcon,
  CAMERA: CameraIcon,
  CAMERA_HD: Camera01Icon,
  CHESS: Chess01Icon,
  CHESS_KING: ChessKingIcon,
  CODE_TERMINAL: ComputerTerminalIcon,
  COOKBOOK: CookBookIcon,
  DUMBBELL: Dumbbell01Icon,
  FILM: Film01Icon,
  FOOTBALL: FootballIcon,
  GAME_CONTROLLER: GameController01Icon,
  GLOBE: GlobeIcon,
  KNOWLEDGE: Knowledge01Icon,
  LAUREL_WREATH: LaurelWreath01Icon,
  LEAF: Leaf01Icon,
  MEGAPHONE: MegaphoneIcon,
  MORTARBOARD: Mortarboard01Icon,
  MUSIC_NOTE: MusicNote02Icon,
  PAINT_BOARD: PaintBoardIcon,
  STAR: StarIcon,
  SUPER_MARIO: SuperMarioIcon,
  SWIMMING: SwimmingIcon,
  TENNIS_RACKET: TennisRacketIcon,
  TEST_TUBE: TestTube01Icon,
  THEATER_MASK: MaskTheaterIcon,
  TREE: TreeIcon,
  VOLLEYBALL: VolleyballIcon,
} as const satisfies Record<string, Hugeicon>;

export type ClubIconKey = keyof typeof ALLOWED_ICON_MAP;

export const ALLOWED_COLOR_VALUES = Object.keys(CLUB_COLOR_HEX) as ClubColor[];
export const ALLOWED_ICON_VALUES = Object.keys(
  ALLOWED_ICON_MAP,
) as ClubIconKey[];
