/*
Midreport SQL databse creation file.
Team lead: Adam Mahres < 158277 >
Date: 23/03/2026 16;46
Course: SP26-CSC332602 Database Systems
Shortcut: psql -U lfirstname -f create.sql
*/

DROP DATABASE IF EXISTS aui_clubs;

CREATE DATABASE aui_clubs;

\c aui_clubs;

CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    fname VARCHAR(50) NOT NULL,
    lname VARCHAR(50) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(120) NOT NULL,
    is_system_admin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE club (
    club_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    main_color VARCHAR(30),
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    email VARCHAR(100) NOT NULL UNIQUE,
    icon_name VARCHAR(40),
    CONSTRAINT fk_club_owner FOREIGN KEY (owner_id) REFERENCES users (user_id) ON UPDATE CASCADE,
    CONSTRAINT chk_club_status CHECK (
        status IN ('active', 'deleted', 'archived')
    ),
    CONSTRAINT chk_club_color CHECK (
        main_color IS NULL
        OR UPPER(main_color) IN (
            'BLUE', 'BLACK', 'RED', 'GREEN', 'AMBER',
            'ORANGE', 'YELLOW', 'CYAN', 'PINK', 'PURPLE',
            'SLATE', 'TEAL', 'INDIGO', 'ROSE'
        )
    ),
    CONSTRAINT chk_club_icon_name CHECK (
        icon_name IS NULL
        OR icon_name IN (
            'ADVENTURE', 'AI_SPARKLES', 'BICYCLE', 'BOOK_OPEN', 'BRIEFCASE',
            'CAMERA', 'CAMERA_HD', 'CHESS', 'CHESS_KING', 'CODE_TERMINAL',
            'COOKBOOK', 'DUMBBELL', 'FILM', 'FOOTBALL', 'GAME_CONTROLLER',
            'GLOBE', 'KNOWLEDGE', 'LAUREL_WREATH', 'LEAF', 'MEGAPHONE',
            'MORTARBOARD', 'MUSIC_NOTE', 'PAINT_BOARD', 'STAR', 'SUPER_MARIO',
            'SWIMMING', 'TENNIS_RACKET', 'TEST_TUBE', 'THEATER_MASK', 'TREE',
            'VOLLEYBALL'
        )
    )
);

CREATE TABLE membership (
    membership_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    club_id INT NOT NULL,
    joined_at TIMESTAMP NOT NULL DEFAULT NOW(),
    left_at TIMESTAMP,
    membership_status VARCHAR(20) NOT NULL DEFAULT 'active',
    membership_role VARCHAR(20) NOT NULL DEFAULT 'member',
    invited_by INT,
    CONSTRAINT fk_membership_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE CASCADE,
    CONSTRAINT fk_membership_club FOREIGN KEY (club_id) REFERENCES club (club_id) ON UPDATE CASCADE,
    CONSTRAINT fk_membership_invited FOREIGN KEY (invited_by) REFERENCES users (user_id) ON UPDATE CASCADE,
    CONSTRAINT uq_membership_user_club UNIQUE (user_id, club_id),
    CONSTRAINT chk_membership_status CHECK (
        membership_status IN ('pending', 'active', 'rejected', 'left', 'banned')
    ),
    CONSTRAINT chk_membership_role CHECK (
        membership_role IN ('board_member', 'member')
    )
);

CREATE TABLE post (
    post_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id INT NOT NULL,
    user_id INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_post_club FOREIGN KEY (club_id) REFERENCES club (club_id) ON UPDATE CASCADE,
    CONSTRAINT fk_post_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE CASCADE
);

CREATE TABLE joinrequest (
    request_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initiator_user_id INT NOT NULL,
    target_club_id INT NOT NULL,
    reviewer_user_id INT,
    request_type VARCHAR(50) NOT NULL DEFAULT 'join',
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    message VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    reviewed_at TIMESTAMP,
    CONSTRAINT fk_joinrequest_initiator FOREIGN KEY (initiator_user_id) REFERENCES users (user_id) ON UPDATE CASCADE,
    CONSTRAINT fk_joinrequest_reviewer FOREIGN KEY (reviewer_user_id) REFERENCES users (user_id) ON UPDATE CASCADE,
    CONSTRAINT fk_joinrequest_club FOREIGN KEY (target_club_id) REFERENCES club (club_id) ON UPDATE CASCADE,
    CONSTRAINT chk_joinrequest_status CHECK (
        status IN ('pending', 'approved', 'rejected')
    )
);
