-- db/sql/populate.sql
-- seed data - all passwords are: password

INSERT INTO "user" (user_id, email, fname, lname, display_name, password_hash, is_system_admin, created_at)
VALUES
  (1, 'youssef.elidrissi@aui.ma', 'Youssef', 'El Idrissi', 'Youssef El Idrissi', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', TRUE, NOW() - INTERVAL '356 days'),
  (2, 'mohamed.bennis@aui.ma', 'Mohamed', 'Bennis', 'Mohamed Bennis', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '112 days'),
  (3, 'ahmed.laachir@aui.ma', 'Ahmed', 'Laachir', 'Ahmed Laachir', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '203 days'),
  (4, 'fatima.benali@aui.ma', 'Fatima', 'Benali', 'Fatima Benali', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '315 days'),
  (5, 'amina.elamrani@aui.ma', 'Amina', 'El Amrani', 'Amina El Amrani', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '118 days'),
  (6, 'khadija.elmansouri@aui.ma', 'Khadija', 'El Mansouri', 'Khadija El Mansouri', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '256 days'),
  (7, 'mehdi.bouzidi@aui.ma', 'Mehdi', 'Bouzidi', 'Mehdi Bouzidi', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '313 days'),
  (8, 'hicham.cherkaoui@aui.ma', 'Hicham', 'Cherkaoui', 'Hicham Cherkaoui', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '155 days'),
  (9, 'rachid.elfassi@aui.ma', 'Rachid', 'El Fassi', 'Rachid El Fassi', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '95 days'),
  (10, 'sara.zayani@aui.ma', 'Sara', 'Zayani', 'Sara Zayani', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '72 days'),
  (11, 'samira.maaroufi@aui.ma', 'Samira', 'Maaroufi', 'Samira Maaroufi', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '234 days'),
  (12, 'yassine.ouazzani@aui.ma', 'Yassine', 'Ouazzani', 'Yassine Ouazzani', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '187 days'),
  (13, 'nora.bouchareb@aui.ma', 'Nora', 'Bouchareb', 'Nora Bouchareb', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '289 days'),
  (14, 'salma.benjelloun@aui.ma', 'Salma', 'Benjelloun', 'Salma Benjelloun', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '220 days'),
  (15, 'omar.elhachimi@aui.ma', 'Omar', 'El Hachimi', 'Omar El Hachimi', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '180 days'),
  (16, 'hassan.harrak@aui.ma', 'Hassan', 'Harrak', 'Hassan Harrak', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '44 days'),
  (17, 'abdelkader.naamani@aui.ma', 'Abdelkader', 'Naamani', 'Abdelkader Naamani', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '130 days'),
  (18, 'latifa.ouarzazi@aui.ma', 'Latifa', 'Ouarzazi', 'Latifa Ouarzazi', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '332 days'),
  (19, 'karim.rifi@aui.ma', 'Karim', 'Rifi', 'Karim Rifi', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '359 days'),
  (20, 'soukaina.jabari@aui.ma', 'Soukaina', 'Jabari', 'Soukaina Jabari', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '164 days'),
  (21, 'imane.amrani@aui.ma', 'Imane', 'Amrani', 'Imane Amrani', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '144 days'),
  (22, 'reda.elghazali@aui.ma', 'Reda', 'El Ghazali', 'Reda El Ghazali', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '337 days'),
  (23, 'zakaria.kabbaj@aui.ma', 'Zakaria', 'Kabbaj', 'Zakaria Kabbaj', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '46 days'),
  (24, 'badr.elouardi@aui.ma', 'Badr', 'El Ouardi', 'Badr El Ouardi', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '109 days'),
  (25, 'nabil.skalli@aui.ma', 'Nabil', 'Skalli', 'Nabil Skalli', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '193 days'),
  (26, 'laila.tazi@aui.ma', 'Laila', 'Tazi', 'Laila Tazi', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '377 days'),
  (27, 'hajar.azizi@aui.ma', 'Hajar', 'Azizi', 'Hajar Azizi', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '68 days'),
  (28, 'ibtissam.boushaba@aui.ma', 'Ibtissam', 'Boushaba', 'Ibtissam Boushaba', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '240 days'),
  (29, 'yasmine.chentouf@aui.ma', 'Yasmine', 'Chentouf', 'Yasmine Chentouf', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '54 days'),
  (30, 'malak.elyacoubi@aui.ma', 'Malak', 'El Yacoubi', 'Malak El Yacoubi', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '348 days'),
  (31, 'walid.benbrahim@aui.ma', 'Walid', 'Benbrahim', 'Walid Benbrahim', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '159 days'),
  (32, 'nouhaila.elkoraichi@aui.ma', 'Nouhaila', 'El Koraichi', 'Nouhaila El Koraichi', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '266 days'),
  (33, 'anas.sebti@aui.ma', 'Anas', 'Sebti', 'Anas Sebti', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '86 days'),
  (34, 'samir.elghali@aui.ma', 'Samir', 'El Ghali', 'Samir El Ghali', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '92 days'),
  (35, 'hind.bouchta@aui.ma', 'Hind', 'Bouchta', 'Hind Bouchta', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '384 days'),
  (36, 'nourelhouda.lahlou@aui.ma', 'Nourelhouda', 'Lahlou', 'Nourelhouda Lahlou', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '330 days'),
  (37, 'ghita.akhannouch@aui.ma', 'Ghita', 'Akhannouch', 'Ghita Akhannouch', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '239 days'),
  (38, 'ilham.lamrani@aui.ma', 'Ilham', 'Lamrani', 'Ilham Lamrani', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '284 days'),
  (39, 'saad.elkhatib@aui.ma', 'Saad', 'El Khatib', 'Saad El Khatib', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '343 days'),
  (40, 'zineb.elfadli@aui.ma', 'Zineb', 'El Fadli', 'Zineb El Fadli', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '369 days'),
  (41, 'malika.boutaleb@aui.ma', 'Malika', 'Boutaleb', 'Malika Boutaleb', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '246 days'),
  (42, 'abdellah.elkabbaj@aui.ma', 'Abdellah', 'El Kabbaj', 'Abdellah El Kabbaj', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '77 days'),
  (43, 'fadoua.mrabet@aui.ma', 'Fadoua', 'Mrabet', 'Fadoua Mrabet', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '148 days'),
  (44, 'soufiane.elalami@aui.ma', 'Soufiane', 'El Alami', 'Soufiane El Alami', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '324 days'),
  (45, 'siham.benomar@aui.ma', 'Siham', 'Benomar', 'Siham Benomar', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '374 days'),
  (46, 'rania.hamdouch@aui.ma', 'Rania', 'Hamdouch', 'Rania Hamdouch', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '97 days'),
  (47, 'oussama.tahiri@aui.ma', 'Oussama', 'Tahiri', 'Oussama Tahiri', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '338 days'),
  (48, 'meryem.ouazzani@aui.ma', 'Meryem', 'Ouazzani', 'Meryem Ouazzani', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '393 days'),
  (49, 'raniaa.fellahi@aui.ma', 'Raniaa', 'Fellahi', 'Raniaa Fellahi', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '391 days'),
  (50, 'younes.saidi@aui.ma', 'Younes', 'Saidi', 'Younes Saidi', '$2b$12$wpv0CE6nezvt1rxycRjSZu3/9cSBR84YkwC1RLx1bpyAowiMxOIf.', FALSE, NOW() - INTERVAL '348 days');

INSERT INTO "club" (club_id, owner_id, name, description, created_at, main_color, icon_name, status, email)
VALUES
  (1, 1, 'Photography Club', 'Exploring photography techniques and exhibitions.', NOW() - INTERVAL '189 days', 'ROSE', 'CAMERA', 'active', 'club01@aui.ma'),
  (2, 2, 'Mechatronics Club', 'Hands-on mechatronics projects and workshops.', NOW() - INTERVAL '258 days', 'BLUE', 'CODE_TERMINAL', 'active', 'club02@aui.ma'),
  (3, 3, 'Opera Club', 'Appreciation and study of operatic performance.', NOW() - INTERVAL '83 days', 'AMBER', 'MUSIC_NOTE', 'active', 'club03@aui.ma'),
  (4, 4, 'Robotics Society', 'Build and program robots for competitions.', NOW() - INTERVAL '179 days', 'INDIGO', 'AI_SPARKLES', 'active', 'club04@aui.ma'),
  (5, 5, 'Astronomy Circle', 'Stargazing nights and astrophotography.', NOW() - INTERVAL '71 days', 'PURPLE', 'STAR', 'active', 'club05@aui.ma'),
  (6, 6, 'Chess Club', 'Weekly chess meetups and tournaments.', NOW() - INTERVAL '123 days', 'BLACK', 'CHESS', 'active', 'club06@aui.ma'),
  (7, 7, 'Debate & Rhetoric', 'Debate practice and public speaking coaching.', NOW() - INTERVAL '118 days', 'RED', 'KNOWLEDGE', 'active', 'club07@aui.ma'),
  (8, 8, 'Environmental Action', 'Projects focused on sustainability and campus greening.', NOW() - INTERVAL '126 days', 'GREEN', 'LEAF', 'active', 'club08@aui.ma'),
  (9, 9, 'Film & Media', 'Short film screenings and critiques.', NOW() - INTERVAL '268 days', 'RED', 'FILM', 'active', 'club09@aui.ma'),
  (10, 10, 'Literature Workshop', 'Creative writing and book readings.', NOW() - INTERVAL '50 days', 'ORANGE', 'BOOK_OPEN', 'active', 'club10@aui.ma'),
  (11, 11, 'Coding Guild', 'Collaborative coding projects and hack nights.', NOW() - INTERVAL '292 days', 'SLATE', 'CODE_TERMINAL', 'active', 'club11@aui.ma'),
  (12, 12, 'Entrepreneurship Hub', 'Startup pitches, mentorship, and workshops.', NOW() - INTERVAL '130 days', 'AMBER', 'BRIEFCASE', 'active', 'club12@aui.ma'),
  (13, 13, 'Arabic Calligraphy', 'Practice traditional Arabic calligraphy and exhibitions.', NOW() - INTERVAL '111 days', 'PINK', 'PAINT_BOARD', 'active', 'club13@aui.ma'),
  (14, 14, 'Music Ensemble', 'Small ensembles and concerts.', NOW() - INTERVAL '245 days', 'INDIGO', 'MUSIC_NOTE', 'active', 'club14@aui.ma'),
  (15, 15, 'Culinary Arts', 'Cooking workshops and recipe exchanges.', NOW() - INTERVAL '43 days', 'ROSE', 'COOKBOOK', 'active', 'club15@aui.ma'),
  (16, 16, 'Design & UX', 'Design critiques and portfolio reviews.', NOW() - INTERVAL '127 days', 'PURPLE', 'GLOBE', 'active', 'club16@aui.ma'),
  (17, 17, 'AI Research', 'Study groups and research on AI topics.', NOW() - INTERVAL '189 days', 'SLATE', 'AI_SPARKLES', 'active', 'club17@aui.ma'),
  (18, 18, 'Hiking & Outdoors', 'Hikes, camping trips, and route planning.', NOW() - INTERVAL '166 days', 'GREEN', 'ADVENTURE', 'active', 'club18@aui.ma'),
  (19, 19, 'Model United Nations', 'Simulations and policy debates.', NOW() - INTERVAL '119 days', 'RED', 'MEGAPHONE', 'active', 'club19@aui.ma'),
  (20, 20, 'Photography: Street', 'Street photography walks and critiques.', NOW() - INTERVAL '289 days', 'PINK', 'CAMERA_HD', 'active', 'club20@aui.ma'),
  (21, 21, 'Theatre Troupe', 'Stage productions and acting classes.', NOW() - INTERVAL '261 days', 'ORANGE', 'THEATER_MASK', 'active', 'club21@aui.ma'),
  (22, 22, 'Volunteer Corps', 'Organized volunteer events and service projects.', NOW() - INTERVAL '153 days', 'TEAL', 'VOLLEYBALL', 'active', 'club22@aui.ma'),
  (23, 23, 'Language Exchange', 'Language practice with native speakers.', NOW() - INTERVAL '285 days', 'BLUE', 'GLOBE', 'active', 'club23@aui.ma'),
  (24, 24, 'Art & Illustration', 'Illustration workshops and zine-making.', NOW() - INTERVAL '164 days', 'ROSE', 'PAINT_BOARD', 'active', 'club24@aui.ma'),
  (25, 25, 'Tennis Club', 'Tennis practice and ladder matches.', NOW() - INTERVAL '39 days', 'CYAN', 'TENNIS_RACKET', 'active', 'club25@aui.ma'),
  (26, 26, 'Basketball Club', 'Pickup games and leagues.', NOW() - INTERVAL '176 days', 'AMBER', 'SWIMMING', 'active', 'club26@aui.ma'),
  (27, 27, 'Soccer Fan Club', 'Supporters club for campus soccer.', NOW() - INTERVAL '261 days', 'GREEN', 'FOOTBALL', 'active', 'club27@aui.ma'),
  (28, 28, 'Sound Engineering', 'Live sound workshops and mixing sessions.', NOW() - INTERVAL '73 days', 'BLACK', 'BRIEFCASE', 'active', 'club28@aui.ma'),
  (29, 29, 'Cultural Heritage', 'Research and preservation of local heritage.', NOW() - INTERVAL '46 days', 'PURPLE', 'LAUREL_WREATH', 'active', 'club29@aui.ma'),
  (30, 30, 'Sustainable Farming', 'Permaculture and sustainable gardening.', NOW() - INTERVAL '288 days', 'GREEN', 'TREE', 'active', 'club30@aui.ma'),
  (31, 31, 'Board Games Collective', 'Board game nights and tournaments.', NOW() - INTERVAL '73 days', 'INDIGO', 'GAME_CONTROLLER', 'active', 'club31@aui.ma'),
  (32, 32, 'Math Circle', 'Problem-solving sessions and contests.', NOW() - INTERVAL '72 days', 'ORANGE', 'KNOWLEDGE', 'active', 'club32@aui.ma'),
  (33, 33, 'Physics Society', 'Physics talks and demonstrations.', NOW() - INTERVAL '232 days', 'SLATE', 'TEST_TUBE', 'active', 'club33@aui.ma'),
  (34, 34, 'Biotech Club', 'Biology research projects and labs.', NOW() - INTERVAL '272 days', 'TEAL', 'TEST_TUBE', 'active', 'club34@aui.ma'),
  (35, 35, 'Startup Incubator', 'Hardware-software integration projects.', NOW() - INTERVAL '101 days', 'ROSE', 'BRIEFCASE', 'active', 'club35@aui.ma'),
  (36, 36, 'Journalism Lab', 'Student journalism and reporting.', NOW() - INTERVAL '94 days', 'RED', 'MEGAPHONE', 'active', 'club36@aui.ma'),
  (37, 37, 'Fashion & Textiles', 'Fashion design and workshops.', NOW() - INTERVAL '227 days', 'PINK', 'PAINT_BOARD', 'active', 'club37@aui.ma'),
  (38, 38, 'Poetry & Spoken Word', 'Poetry slams and open mic nights.', NOW() - INTERVAL '147 days', 'PURPLE', 'MORTARBOARD', 'active', 'club38@aui.ma'),
  (39, 39, 'Opera Appreciation', 'Opera listening sessions and guest talks.', NOW() - INTERVAL '124 days', 'AMBER', 'MUSIC_NOTE', 'active', 'club39@aui.ma'),
  (40, 40, 'Classical Music', 'Chamber music rehearsals and recitals.', NOW() - INTERVAL '175 days', 'INDIGO', 'MUSIC_NOTE', 'active', 'club40@aui.ma'),
  (41, 41, 'Dance Collective', 'Choreography and dance practice.', NOW() - INTERVAL '198 days', 'ROSE', 'DUMBBELL', 'active', 'club41@aui.ma'),
  (42, 42, 'Film Production', 'Student film crew and production classes.', NOW() - INTERVAL '14 days', 'ORANGE', 'FILM', 'active', 'club42@aui.ma'),
  (43, 43, 'Digital Arts', 'Digital painting and animation.', NOW() - INTERVAL '275 days', 'PINK', 'STAR', 'active', 'club43@aui.ma'),
  (44, 44, 'Photography: Portrait', 'Studio portrait sessions and lighting techniques.', NOW() - INTERVAL '143 days', 'BLUE', 'CAMERA', 'active', 'club44@aui.ma'),
  (45, 45, 'Adventure Club', 'Outdoor adventure planning and expeditions.', NOW() - INTERVAL '260 days', 'GREEN', 'ADVENTURE', 'active', 'club45@aui.ma'),
  (46, 46, 'Robotics: Drones', 'Drone programming and aerial projects.', NOW() - INTERVAL '295 days', 'SLATE', 'SUPER_MARIO', 'active', 'club46@aui.ma'),
  (47, 47, 'Electronics Lab', 'Electronics prototyping and soldering classes.', NOW() - INTERVAL '44 days', 'BLACK', 'TEST_TUBE', 'active', 'club47@aui.ma'),
  (48, 48, '3D Printing Studio', '3D printing workshops and model fabrication.', NOW() - INTERVAL '277 days', 'AMBER', 'GAME_CONTROLLER', 'active', 'club48@aui.ma'),
  (49, 49, 'Gardening Club', 'Urban gardening and community plots.', NOW() - INTERVAL '217 days', 'GREEN', 'TREE', 'active', 'club49@aui.ma'),
  (50, 50, 'Community Outreach', 'Local outreach and partner events.', NOW() - INTERVAL '26 days', 'TEAL', 'MEGAPHONE', 'active', 'club50@aui.ma');

INSERT INTO "membership" (membership_id, user_id, club_id, joined_at, membership_role)
VALUES
  (1, 1, 1, NOW() - INTERVAL '59 days', 'board_member'),
  (2, 2, 1, NOW() - INTERVAL '64 days', 'board_member'),
  (3, 3, 1, NOW() - INTERVAL '98 days', 'board_member'),
  (4, 4, 1, NOW() - INTERVAL '91 days', 'board_member'),
  (5, 5, 1, NOW() - INTERVAL '76 days', 'board_member'),
  (6, 6, 1, NOW() - INTERVAL '10 days', 'member'),
  (7, 7, 1, NOW() - INTERVAL '50 days', 'member'),
  (8, 8, 1, NOW() - INTERVAL '59 days', 'member'),
  (9, 9, 1, NOW() - INTERVAL '27 days', 'member'),
  (10, 10, 1, NOW() - INTERVAL '94 days', 'member'),
  (11, 11, 1, NOW() - INTERVAL '16 days', 'member'),
  (12, 12, 1, NOW() - INTERVAL '22 days', 'member'),
  (13, 13, 1, NOW() - INTERVAL '16 days', 'member'),
  (14, 14, 1, NOW() - INTERVAL '30 days', 'member'),
  (15, 15, 1, NOW() - INTERVAL '40 days', 'member'),
  (16, 16, 1, NOW() - INTERVAL '3 days', 'member'),
  (17, 17, 1, NOW() - INTERVAL '42 days', 'member'),
  (18, 18, 1, NOW() - INTERVAL '49 days', 'member'),
  (19, 19, 1, NOW() - INTERVAL '54 days', 'member'),
  (20, 20, 1, NOW() - INTERVAL '27 days', 'member'),
  (21, 3, 3, NOW() - INTERVAL '136 days', 'board_member'),
  (22, 10, 3, NOW() - INTERVAL '62 days', 'member'),
  (23, 11, 3, NOW() - INTERVAL '23 days', 'member'),
  (24, 12, 3, NOW() - INTERVAL '36 days', 'member'),
  (25, 13, 3, NOW() - INTERVAL '27 days', 'member'),
  (26, 4, 4, NOW() - INTERVAL '52 days', 'board_member'),
  (27, 20, 4, NOW() - INTERVAL '43 days', 'member'),
  (28, 21, 4, NOW() - INTERVAL '83 days', 'member'),
  (29, 22, 4, NOW() - INTERVAL '34 days', 'member'),
  (30, 23, 4, NOW() - INTERVAL '93 days', 'member'),
  (31, 24, 4, NOW() - INTERVAL '30 days', 'member'),
  (32, 25, 4, NOW() - INTERVAL '109 days', 'member'),
  (33, 26, 4, NOW() - INTERVAL '151 days', 'member'),
  (34, 27, 4, NOW() - INTERVAL '94 days', 'member'),
  (35, 28, 4, NOW() - INTERVAL '47 days', 'member'),
  (36, 2, 2, NOW() - INTERVAL '10 days', 'board_member'),
  (37, 5, 5, NOW() - INTERVAL '10 days', 'board_member'),
  (38, 6, 6, NOW() - INTERVAL '10 days', 'board_member'),
  (39, 7, 7, NOW() - INTERVAL '10 days', 'board_member'),
  (40, 8, 8, NOW() - INTERVAL '10 days', 'board_member'),
  (41, 9, 9, NOW() - INTERVAL '10 days', 'board_member'),
  (42, 10, 10, NOW() - INTERVAL '10 days', 'board_member'),
  (43, 11, 11, NOW() - INTERVAL '10 days', 'board_member'),
  (44, 12, 12, NOW() - INTERVAL '10 days', 'board_member'),
  (45, 13, 13, NOW() - INTERVAL '10 days', 'board_member'),
  (46, 14, 14, NOW() - INTERVAL '10 days', 'board_member'),
  (47, 15, 15, NOW() - INTERVAL '10 days', 'board_member'),
  (48, 16, 16, NOW() - INTERVAL '10 days', 'board_member'),
  (49, 17, 17, NOW() - INTERVAL '10 days', 'board_member'),
  (50, 18, 18, NOW() - INTERVAL '10 days', 'board_member'),
  (51, 19, 19, NOW() - INTERVAL '10 days', 'board_member'),
  (52, 20, 20, NOW() - INTERVAL '10 days', 'board_member'),
  (53, 21, 21, NOW() - INTERVAL '10 days', 'board_member'),
  (54, 22, 22, NOW() - INTERVAL '10 days', 'board_member'),
  (55, 23, 23, NOW() - INTERVAL '10 days', 'board_member'),
  (56, 24, 24, NOW() - INTERVAL '10 days', 'board_member'),
  (57, 25, 25, NOW() - INTERVAL '10 days', 'board_member'),
  (58, 26, 26, NOW() - INTERVAL '10 days', 'board_member'),
  (59, 27, 27, NOW() - INTERVAL '10 days', 'board_member'),
  (60, 28, 28, NOW() - INTERVAL '10 days', 'board_member'),
  (61, 29, 29, NOW() - INTERVAL '10 days', 'board_member'),
  (62, 30, 30, NOW() - INTERVAL '10 days', 'board_member'),
  (63, 31, 31, NOW() - INTERVAL '10 days', 'board_member'),
  (64, 32, 32, NOW() - INTERVAL '10 days', 'board_member'),
  (65, 33, 33, NOW() - INTERVAL '10 days', 'board_member'),
  (66, 34, 34, NOW() - INTERVAL '10 days', 'board_member'),
  (67, 35, 35, NOW() - INTERVAL '10 days', 'board_member'),
  (68, 36, 36, NOW() - INTERVAL '10 days', 'board_member'),
  (69, 37, 37, NOW() - INTERVAL '10 days', 'board_member'),
  (70, 38, 38, NOW() - INTERVAL '10 days', 'board_member'),
  (71, 39, 39, NOW() - INTERVAL '10 days', 'board_member'),
  (72, 40, 40, NOW() - INTERVAL '10 days', 'board_member'),
  (73, 41, 41, NOW() - INTERVAL '10 days', 'board_member'),
  (74, 42, 42, NOW() - INTERVAL '10 days', 'board_member'),
  (75, 43, 43, NOW() - INTERVAL '10 days', 'board_member'),
  (76, 44, 44, NOW() - INTERVAL '10 days', 'board_member'),
  (77, 45, 45, NOW() - INTERVAL '10 days', 'board_member'),
  (78, 46, 46, NOW() - INTERVAL '10 days', 'board_member'),
  (79, 47, 47, NOW() - INTERVAL '10 days', 'board_member'),
  (80, 48, 48, NOW() - INTERVAL '10 days', 'board_member'),
  (81, 49, 49, NOW() - INTERVAL '10 days', 'board_member'),
  (82, 50, 50, NOW() - INTERVAL '10 days', 'board_member'),
  (83, 50, 25, NOW() - INTERVAL '174 days', 'member'),
  (84, 19, 32, NOW() - INTERVAL '97 days', 'member'),
  (85, 2, 25, NOW() - INTERVAL '51 days', 'member'),
  (86, 36, 30, NOW() - INTERVAL '278 days', 'member'),
  (87, 49, 42, NOW() - INTERVAL '121 days', 'member'),
  (88, 45, 48, NOW() - INTERVAL '213 days', 'member'),
  (89, 10, 17, NOW() - INTERVAL '288 days', 'member'),
  (90, 18, 23, NOW() - INTERVAL '61 days', 'member'),
  (91, 30, 44, NOW() - INTERVAL '110 days', 'member'),
  (92, 1, 6, NOW() - INTERVAL '193 days', 'member'),
  (93, 26, 3, NOW() - INTERVAL '108 days', 'member'),
  (94, 39, 28, NOW() - INTERVAL '211 days', 'member'),
  (95, 33, 47, NOW() - INTERVAL '41 days', 'member'),
  (96, 9, 49, NOW() - INTERVAL '286 days', 'member'),
  (97, 36, 42, NOW() - INTERVAL '19 days', 'member'),
  (98, 42, 39, NOW() - INTERVAL '64 days', 'member'),
  (99, 18, 29, NOW() - INTERVAL '111 days', 'member'),
  (100, 14, 29, NOW() - INTERVAL '172 days', 'member'),
  (101, 40, 33, NOW() - INTERVAL '232 days', 'member'),
  (102, 50, 49, NOW() - INTERVAL '218 days', 'member'),
  (103, 14, 33, NOW() - INTERVAL '1 days', 'member'),
  (104, 35, 22, NOW() - INTERVAL '273 days', 'member'),
  (105, 47, 33, NOW() - INTERVAL '58 days', 'member'),
  (106, 18, 44, NOW() - INTERVAL '108 days', 'member'),
  (107, 14, 48, NOW() - INTERVAL '87 days', 'member'),
  (108, 7, 8, NOW() - INTERVAL '76 days', 'member'),
  (109, 28, 41, NOW() - INTERVAL '113 days', 'member'),
  (110, 17, 10, NOW() - INTERVAL '129 days', 'member'),
  (111, 50, 47, NOW() - INTERVAL '171 days', 'member'),
  (112, 21, 23, NOW() - INTERVAL '204 days', 'member'),
  (113, 32, 43, NOW() - INTERVAL '265 days', 'member'),
  (114, 10, 20, NOW() - INTERVAL '228 days', 'member'),
  (115, 21, 2, NOW() - INTERVAL '65 days', 'member'),
  (116, 43, 45, NOW() - INTERVAL '10 days', 'member'),
  (117, 33, 36, NOW() - INTERVAL '202 days', 'member'),
  (118, 49, 16, NOW() - INTERVAL '275 days', 'member'),
  (119, 44, 22, NOW() - INTERVAL '60 days', 'member'),
  (120, 30, 28, NOW() - INTERVAL '107 days', 'member'),
  (121, 18, 41, NOW() - INTERVAL '265 days', 'member'),
  (122, 44, 28, NOW() - INTERVAL '9 days', 'member'),
  (123, 41, 3, NOW() - INTERVAL '46 days', 'member'),
  (124, 10, 23, NOW() - INTERVAL '201 days', 'member'),
  (125, 34, 42, NOW() - INTERVAL '278 days', 'member'),
  (126, 47, 44, NOW() - INTERVAL '218 days', 'member'),
  (127, 19, 34, NOW() - INTERVAL '20 days', 'member'),
  (128, 39, 10, NOW() - INTERVAL '241 days', 'member'),
  (129, 41, 47, NOW() - INTERVAL '154 days', 'member'),
  (130, 36, 10, NOW() - INTERVAL '14 days', 'member'),
  (131, 47, 46, NOW() - INTERVAL '295 days', 'member'),
  (132, 19, 9, NOW() - INTERVAL '164 days', 'member'),
  (133, 20, 50, NOW() - INTERVAL '5 days', 'member'),
  (134, 20, 12, NOW() - INTERVAL '290 days', 'member'),
  (135, 4, 13, NOW() - INTERVAL '46 days', 'member'),
  (136, 34, 39, NOW() - INTERVAL '262 days', 'member'),
  (137, 1, 47, NOW() - INTERVAL '24 days', 'member'),
  (138, 2, 10, NOW() - INTERVAL '39 days', 'member'),
  (139, 24, 39, NOW() - INTERVAL '5 days', 'member'),
  (140, 21, 33, NOW() - INTERVAL '118 days', 'member'),
  (141, 11, 49, NOW() - INTERVAL '152 days', 'member'),
  (142, 48, 36, NOW() - INTERVAL '199 days', 'member'),
  (143, 25, 19, NOW() - INTERVAL '188 days', 'member'),
  (144, 6, 43, NOW() - INTERVAL '124 days', 'member'),
  (145, 9, 6, NOW() - INTERVAL '112 days', 'member'),
  (146, 22, 14, NOW() - INTERVAL '102 days', 'member'),
  (147, 26, 1, NOW() - INTERVAL '282 days', 'member'),
  (148, 40, 19, NOW() - INTERVAL '207 days', 'member'),
  (149, 45, 25, NOW() - INTERVAL '96 days', 'member'),
  (150, 3, 40, NOW() - INTERVAL '29 days', 'member'),
  (151, 41, 10, NOW() - INTERVAL '277 days', 'member'),
  (152, 10, 46, NOW() - INTERVAL '200 days', 'member'),
  (153, 28, 43, NOW() - INTERVAL '22 days', 'member'),
  (154, 31, 34, NOW() - INTERVAL '102 days', 'member'),
  (155, 12, 13, NOW() - INTERVAL '30 days', 'member'),
  (156, 5, 11, NOW() - INTERVAL '292 days', 'member'),
  (157, 40, 45, NOW() - INTERVAL '278 days', 'member'),
  (158, 16, 40, NOW() - INTERVAL '51 days', 'member'),
  (159, 12, 33, NOW() - INTERVAL '57 days', 'member'),
  (160, 10, 49, NOW() - INTERVAL '113 days', 'member'),
  (161, 37, 19, NOW() - INTERVAL '84 days', 'member'),
  (162, 41, 46, NOW() - INTERVAL '180 days', 'member'),
  (163, 19, 28, NOW() - INTERVAL '57 days', 'member'),
  (164, 16, 35, NOW() - INTERVAL '79 days', 'member'),
  (165, 26, 40, NOW() - INTERVAL '277 days', 'member'),
  (166, 36, 40, NOW() - INTERVAL '183 days', 'member'),
  (167, 28, 32, NOW() - INTERVAL '87 days', 'member'),
  (168, 40, 7, NOW() - INTERVAL '63 days', 'member'),
  (169, 18, 16, NOW() - INTERVAL '102 days', 'member'),
  (170, 25, 50, NOW() - INTERVAL '214 days', 'member'),
  (171, 19, 23, NOW() - INTERVAL '292 days', 'member'),
  (172, 31, 38, NOW() - INTERVAL '300 days', 'member'),
  (173, 27, 18, NOW() - INTERVAL '192 days', 'member'),
  (174, 14, 32, NOW() - INTERVAL '296 days', 'member'),
  (175, 30, 36, NOW() - INTERVAL '210 days', 'member'),
  (176, 39, 20, NOW() - INTERVAL '16 days', 'member'),
  (177, 5, 48, NOW() - INTERVAL '154 days', 'member'),
  (178, 46, 40, NOW() - INTERVAL '186 days', 'member'),
  (179, 41, 15, NOW() - INTERVAL '108 days', 'member'),
  (180, 49, 48, NOW() - INTERVAL '14 days', 'member'),
  (181, 3, 13, NOW() - INTERVAL '46 days', 'member'),
  (182, 35, 1, NOW() - INTERVAL '52 days', 'member'),
  (183, 1, 39, NOW() - INTERVAL '53 days', 'member'),
  (184, 19, 14, NOW() - INTERVAL '8 days', 'member'),
  (185, 11, 39, NOW() - INTERVAL '12 days', 'member'),
  (186, 38, 20, NOW() - INTERVAL '256 days', 'member'),
  (187, 36, 2, NOW() - INTERVAL '281 days', 'member'),
  (188, 9, 19, NOW() - INTERVAL '189 days', 'member'),
  (189, 49, 35, NOW() - INTERVAL '198 days', 'member'),
  (190, 49, 45, NOW() - INTERVAL '60 days', 'member'),
  (191, 10, 6, NOW() - INTERVAL '201 days', 'member'),
  (192, 13, 18, NOW() - INTERVAL '74 days', 'member'),
  (193, 48, 45, NOW() - INTERVAL '94 days', 'member'),
  (194, 12, 20, NOW() - INTERVAL '277 days', 'member'),
  (195, 25, 40, NOW() - INTERVAL '232 days', 'member'),
  (196, 23, 3, NOW() - INTERVAL '171 days', 'member'),
  (197, 31, 36, NOW() - INTERVAL '78 days', 'member'),
  (198, 4, 24, NOW() - INTERVAL '269 days', 'member'),
  (199, 39, 31, NOW() - INTERVAL '118 days', 'member'),
  (200, 1, 29, NOW() - INTERVAL '21 days', 'member'),
  (201, 16, 8, NOW() - INTERVAL '200 days', 'member'),
  (202, 26, 21, NOW() - INTERVAL '101 days', 'member'),
  (203, 37, 18, NOW() - INTERVAL '67 days', 'member'),
  (204, 39, 16, NOW() - INTERVAL '206 days', 'member'),
  (205, 49, 10, NOW() - INTERVAL '106 days', 'member'),
  (206, 22, 12, NOW() - INTERVAL '97 days', 'member'),
  (207, 30, 7, NOW() - INTERVAL '93 days', 'member'),
  (208, 26, 48, NOW() - INTERVAL '5 days', 'member'),
  (209, 5, 49, NOW() - INTERVAL '197 days', 'member'),
  (210, 9, 5, NOW() - INTERVAL '112 days', 'member'),
  (211, 9, 33, NOW() - INTERVAL '7 days', 'member'),
  (212, 45, 11, NOW() - INTERVAL '165 days', 'member'),
  (213, 17, 11, NOW() - INTERVAL '116 days', 'member'),
  (214, 26, 30, NOW() - INTERVAL '261 days', 'member'),
  (215, 44, 3, NOW() - INTERVAL '67 days', 'member'),
  (216, 25, 3, NOW() - INTERVAL '74 days', 'member'),
  (217, 10, 44, NOW() - INTERVAL '244 days', 'member'),
  (218, 44, 43, NOW() - INTERVAL '38 days', 'member'),
  (219, 39, 7, NOW() - INTERVAL '249 days', 'member'),
  (220, 11, 38, NOW() - INTERVAL '99 days', 'member'),
  (221, 31, 18, NOW() - INTERVAL '97 days', 'member'),
  (222, 32, 50, NOW() - INTERVAL '13 days', 'member'),
  (223, 43, 44, NOW() - INTERVAL '12 days', 'member'),
  (224, 47, 41, NOW() - INTERVAL '91 days', 'member'),
  (225, 2, 40, NOW() - INTERVAL '233 days', 'member');

INSERT INTO "post" (post_id, club_id, user_id, title, content, created_at, updated_at, is_deleted, is_pinned, like_count)
VALUES
  (1, 1, 1, 'Photography Club kickoff', 'Welcome to Photography Club. Let''''s share ideas and projects!', NOW() - INTERVAL '14 days', NULL, FALSE, FALSE, 0),
  (2, 2, 2, 'Mechatronics Club kickoff', 'Welcome to Mechatronics Club. Let''''s share ideas and projects!', NOW() - INTERVAL '19 days', NULL, FALSE, FALSE, 0),
  (3, 3, 3, 'Opera Club kickoff', 'Welcome to Opera Club. Let''''s share ideas and projects!', NOW() - INTERVAL '2 days', NULL, FALSE, FALSE, 0),
  (4, 4, 4, 'Robotics Society kickoff', 'Welcome to Robotics Society. Let''''s share ideas and projects!', NOW() - INTERVAL '47 days', NULL, FALSE, FALSE, 0),
  (5, 5, 5, 'Astronomy Circle kickoff', 'Welcome to Astronomy Circle. Let''''s share ideas and projects!', NOW() - INTERVAL '27 days', NULL, FALSE, FALSE, 0),
  (6, 6, 6, 'Chess Club kickoff', 'Welcome to Chess Club. Let''''s share ideas and projects!', NOW() - INTERVAL '9 days', NULL, FALSE, FALSE, 0),
  (7, 7, 7, 'Debate & Rhetoric kickoff', 'Welcome to Debate & Rhetoric. Let''''s share ideas and projects!', NOW() - INTERVAL '29 days', NULL, FALSE, FALSE, 0),
  (8, 8, 8, 'Environmental Action kickoff', 'Welcome to Environmental Action. Let''''s share ideas and projects!', NOW() - INTERVAL '24 days', NULL, FALSE, FALSE, 0),
  (9, 9, 9, 'Film & Media kickoff', 'Welcome to Film & Media. Let''''s share ideas and projects!', NOW() - INTERVAL '20 days', NULL, FALSE, FALSE, 0),
  (10, 10, 10, 'Literature Workshop kickoff', 'Welcome to Literature Workshop. Let''''s share ideas and projects!', NOW() - INTERVAL '25 days', NULL, FALSE, FALSE, 0),
  (11, 11, 11, 'Coding Guild kickoff', 'Welcome to Coding Guild. Let''''s share ideas and projects!', NOW() - INTERVAL '6 days', NULL, FALSE, FALSE, 0),
  (12, 12, 12, 'Entrepreneurship Hub kickoff', 'Welcome to Entrepreneurship Hub. Let''''s share ideas and projects!', NOW() - INTERVAL '47 days', NULL, FALSE, FALSE, 0),
  (13, 13, 13, 'Arabic Calligraphy kickoff', 'Welcome to Arabic Calligraphy. Let''''s share ideas and projects!', NOW() - INTERVAL '21 days', NULL, FALSE, FALSE, 0),
  (14, 14, 14, 'Music Ensemble kickoff', 'Welcome to Music Ensemble. Let''''s share ideas and projects!', NOW() - INTERVAL '48 days', NULL, FALSE, FALSE, 0),
  (15, 15, 15, 'Culinary Arts kickoff', 'Welcome to Culinary Arts. Let''''s share ideas and projects!', NOW() - INTERVAL '5 days', NULL, FALSE, FALSE, 0),
  (16, 16, 16, 'Design & UX kickoff', 'Welcome to Design & UX. Let''''s share ideas and projects!', NOW() - INTERVAL '29 days', NULL, FALSE, FALSE, 0),
  (17, 17, 17, 'AI Research kickoff', 'Welcome to AI Research. Let''''s share ideas and projects!', NOW() - INTERVAL '15 days', NULL, FALSE, FALSE, 0),
  (18, 18, 18, 'Hiking & Outdoors kickoff', 'Welcome to Hiking & Outdoors. Let''''s share ideas and projects!', NOW() - INTERVAL '26 days', NULL, FALSE, FALSE, 0),
  (19, 19, 19, 'Model United Nations kickoff', 'Welcome to Model United Nations. Let''''s share ideas and projects!', NOW() - INTERVAL '11 days', NULL, FALSE, FALSE, 0),
  (20, 20, 20, 'Photography: Street kickoff', 'Welcome to Photography: Street. Let''''s share ideas and projects!', NOW() - INTERVAL '40 days', NULL, FALSE, FALSE, 0),
  (21, 21, 21, 'Theatre Troupe kickoff', 'Welcome to Theatre Troupe. Let''''s share ideas and projects!', NOW() - INTERVAL '6 days', NULL, FALSE, FALSE, 0),
  (22, 22, 22, 'Volunteer Corps kickoff', 'Welcome to Volunteer Corps. Let''''s share ideas and projects!', NOW() - INTERVAL '36 days', NULL, FALSE, FALSE, 0),
  (23, 23, 23, 'Language Exchange kickoff', 'Welcome to Language Exchange. Let''''s share ideas and projects!', NOW() - INTERVAL '8 days', NULL, FALSE, FALSE, 0),
  (24, 24, 24, 'Art & Illustration kickoff', 'Welcome to Art & Illustration. Let''''s share ideas and projects!', NOW() - INTERVAL '41 days', NULL, FALSE, FALSE, 0),
  (25, 25, 25, 'Tennis Club kickoff', 'Welcome to Tennis Club. Let''''s share ideas and projects!', NOW() - INTERVAL '3 days', NULL, FALSE, FALSE, 0),
  (26, 26, 26, 'Basketball Club kickoff', 'Welcome to Basketball Club. Let''''s share ideas and projects!', NOW() - INTERVAL '13 days', NULL, FALSE, FALSE, 0),
  (27, 27, 27, 'Soccer Fan Club kickoff', 'Welcome to Soccer Fan Club. Let''''s share ideas and projects!', NOW() - INTERVAL '36 days', NULL, FALSE, FALSE, 0),
  (28, 28, 28, 'Sound Engineering kickoff', 'Welcome to Sound Engineering. Let''''s share ideas and projects!', NOW() - INTERVAL '19 days', NULL, FALSE, FALSE, 0),
  (29, 29, 29, 'Cultural Heritage kickoff', 'Welcome to Cultural Heritage. Let''''s share ideas and projects!', NOW() - INTERVAL '46 days', NULL, FALSE, FALSE, 0),
  (30, 30, 30, 'Sustainable Farming kickoff', 'Welcome to Sustainable Farming. Let''''s share ideas and projects!', NOW() - INTERVAL '5 days', NULL, FALSE, FALSE, 0),
  (31, 31, 31, 'Board Games Collective kickoff', 'Welcome to Board Games Collective. Let''''s share ideas and projects!', NOW() - INTERVAL '19 days', NULL, FALSE, FALSE, 0),
  (32, 32, 32, 'Math Circle kickoff', 'Welcome to Math Circle. Let''''s share ideas and projects!', NOW() - INTERVAL '20 days', NULL, FALSE, FALSE, 0),
  (33, 33, 33, 'Physics Society kickoff', 'Welcome to Physics Society. Let''''s share ideas and projects!', NOW() - INTERVAL '28 days', NULL, FALSE, FALSE, 0),
  (34, 34, 34, 'Biotech Club kickoff', 'Welcome to Biotech Club. Let''''s share ideas and projects!', NOW() - INTERVAL '15 days', NULL, FALSE, FALSE, 0),
  (35, 35, 35, 'Startup Incubator kickoff', 'Welcome to Startup Incubator. Let''''s share ideas and projects!', NOW() - INTERVAL '10 days', NULL, FALSE, FALSE, 0),
  (36, 36, 36, 'Journalism Lab kickoff', 'Welcome to Journalism Lab. Let''''s share ideas and projects!', NOW() - INTERVAL '33 days', NULL, FALSE, FALSE, 0),
  (37, 37, 37, 'Fashion & Textiles kickoff', 'Welcome to Fashion & Textiles. Let''''s share ideas and projects!', NOW() - INTERVAL '20 days', NULL, FALSE, FALSE, 0),
  (38, 38, 38, 'Poetry & Spoken Word kickoff', 'Welcome to Poetry & Spoken Word. Let''''s share ideas and projects!', NOW() - INTERVAL '17 days', NULL, FALSE, FALSE, 0),
  (39, 39, 39, 'Opera Appreciation kickoff', 'Welcome to Opera Appreciation. Let''''s share ideas and projects!', NOW() - INTERVAL '10 days', NULL, FALSE, FALSE, 0),
  (40, 40, 40, 'Classical Music kickoff', 'Welcome to Classical Music. Let''''s share ideas and projects!', NOW() - INTERVAL '23 days', NULL, FALSE, FALSE, 0),
  (41, 41, 41, 'Dance Collective kickoff', 'Welcome to Dance Collective. Let''''s share ideas and projects!', NOW() - INTERVAL '12 days', NULL, FALSE, FALSE, 0),
  (42, 42, 42, 'Film Production kickoff', 'Welcome to Film Production. Let''''s share ideas and projects!', NOW() - INTERVAL '48 days', NULL, FALSE, FALSE, 0),
  (43, 43, 43, 'Digital Arts kickoff', 'Welcome to Digital Arts. Let''''s share ideas and projects!', NOW() - INTERVAL '18 days', NULL, FALSE, FALSE, 0),
  (44, 44, 44, 'Photography: Portrait kickoff', 'Welcome to Photography: Portrait. Let''''s share ideas and projects!', NOW() - INTERVAL '27 days', NULL, FALSE, FALSE, 0),
  (45, 45, 45, 'Adventure Club kickoff', 'Welcome to Adventure Club. Let''''s share ideas and projects!', NOW() - INTERVAL '43 days', NULL, FALSE, FALSE, 0),
  (46, 46, 46, 'Robotics: Drones kickoff', 'Welcome to Robotics: Drones. Let''''s share ideas and projects!', NOW() - INTERVAL '29 days', NULL, FALSE, FALSE, 0),
  (47, 47, 47, 'Electronics Lab kickoff', 'Welcome to Electronics Lab. Let''''s share ideas and projects!', NOW() - INTERVAL '50 days', NULL, FALSE, FALSE, 0),
  (48, 48, 48, '3D Printing Studio kickoff', 'Welcome to 3D Printing Studio. Let''''s share ideas and projects!', NOW() - INTERVAL '44 days', NULL, FALSE, FALSE, 0),
  (49, 49, 49, 'Gardening Club kickoff', 'Welcome to Gardening Club. Let''''s share ideas and projects!', NOW() - INTERVAL '20 days', NULL, FALSE, FALSE, 0),
  (50, 50, 50, 'Community Outreach kickoff', 'Welcome to Community Outreach. Let''''s share ideas and projects!', NOW() - INTERVAL '50 days', NULL, FALSE, FALSE, 0);

INSERT INTO "post_like" (post_id, user_id, created_at)
VALUES
  (1, 2, NOW() - INTERVAL '1 hour'),
  (2, 3, NOW() - INTERVAL '2 hours'),
  (3, 4, NOW() - INTERVAL '3 hours');

INSERT INTO "joinrequest" (request_id, initiator_user_id, target_club_id, status, message, created_at, reviewed_at)
VALUES
  (1, 2, 5, 'pending', 'Want to stay active and improve my fitness outside of class.', NOW() - INTERVAL '3 days', NULL),
  (2, 5, 1, 'pending', 'Critical thinking and argumentation are skills I really want to develop.', NOW() - INTERVAL '1 day', NULL),
  (3, 9, 1, 'approved', 'Love debate and critical thinking. Was on my high school team.', NOW() - INTERVAL '125 days', NOW() - INTERVAL '124 days');

INSERT INTO "club_creation_request" (request_id, initiator_user_id, name, description, main_color, icon_name, email, status, created_at, reviewed_at)
VALUES
  (1, 8, 'Art & Design Club', 'Workshops on painting, illustration, digital art, and mixed media.', 'PINK', 'PAINT_BOARD', 'artdesign@aui.ma', 'pending', NOW() - INTERVAL '3 days', NULL),
  (2, 10, 'Tennis Club', 'Weekly tennis drills, friendly matches, and court booking coordination.', 'CYAN', 'TENNIS_RACKET', 'tennis@aui.ma', 'pending', NOW() - INTERVAL '9 days', NULL),
  (3, 17, 'Adventure Club', 'Hiking, camping, orienteering, and outdoor survival skills.', 'GREEN', 'ADVENTURE', 'adventure@aui.ma', 'pending', NOW() - INTERVAL '2 weeks', NULL);

INSERT INTO "invite" (invite_id, inviter_user_id, invitee_user_id, club_id, status, message, created_at, responded_at)
VALUES
  (1, 1, 2, 1, 'pending', 'Join Photography Club this week?', NOW() - INTERVAL '4 hours', NULL),
  (2, 12, 13, 12, 'accepted', 'We would love your help with startup talks.', NOW() - INTERVAL '8 days', NOW() - INTERVAL '7 days'),
  (3, 25, 26, 25, 'pending', 'Need another player for Tennis Club drills.', NOW() - INTERVAL '2 weeks', NULL);
