-- db/sql/populate.sql
-- seed data — all passwords are: Password123!

INSERT INTO users (user_id, email, fname, lname, display_name, password_hash, is_system_admin, created_at)
VALUES
  (1,  'admin@aui.ma',                'System',         'Admin',        'AUI Admin',             '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', TRUE,  NOW() - INTERVAL '180 days'),
  (2,  'adam.mahres@aui.ma',          'Adam',           'Mahres',       'Adam Mahres',           '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '160 days'),
  (3,  'mohammed.elmoubaraki@aui.ma', 'Mohammed',       'El Moubaraki', 'Mohammed El Moubaraki', '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '155 days'),
  (4,  'malik.lahlou@aui.ma',         'Mohammed Malik', 'Lahlou',       'Mohammed Malik Lahlou', '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '150 days'),
  (5,  'mouad.ezzahr@aui.ma',         'Mouad',          'Ezzahr',       'Mouad Ezzahr',          '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '148 days'),
  (6,  'rayane.fajri@aui.ma',         'Rayane',         'Fajri',        'Rayane Fajri',          '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '145 days'),
  (7,  'nasser.assem@aui.ma',         'Nasser',         'Assem',        'Nasser Assem',          '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', TRUE,  NOW() - INTERVAL '140 days'),
  (8,  'ahmed.bennani@aui.ma',        'Ahmed',          'Bennani',      'Ahmed Bennani',         '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '135 days'),
  (9,  'leila.rachidi@aui.ma',        'Leila',          'Rachidi',      'Leila Rachidi',         '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '130 days'),
  (10, 'karim.alaoui@aui.ma',         'Karim',          'Alaoui',       'Karim Alaoui',          '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '128 days'),
  (11, 'amal.harkat@aui.ma',          'Amal',           'Harkat',       'Amal Harkat',           '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '125 days'),
  (12, 'hassan.boudri@aui.ma',        'Hassan',         'Boudri',       'Hassan Boudri',         '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '120 days'),
  (13, 'souad.mezouari@aui.ma',       'Souad',          'Mezouari',     'Souad Mezouari',        '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '118 days'),
  (14, 'yasmin.tazi@aui.ma',          'Yasmin',         'Tazi',         'Yasmin Tazi',           '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '115 days'),
  (15, 'samir.chakir@aui.ma',         'Samir',          'Chakir',       'Samir Chakir',          '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '112 days'),
  (16, 'zainab.boutaleb@aui.ma',      'Zainab',         'Boutaleb',     'Zainab Boutaleb',       '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '110 days'),
  (17, 'omar.benali@aui.ma',          'Omar',           'Benali',       'Omar Benali',           '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '105 days'),
  (18, 'fatima.khalil@aui.ma',        'Fatima',         'Khalil',       'Fatima Khalil',         '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '100 days'),
  (19, 'youssef.nadiri@aui.ma',       'Youssef',        'Nadiri',       'Youssef Nadiri',        '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '98 days'),
  (20, 'sara.idrissi@aui.ma',         'Sara',           'Idrissi',      'Sara Idrissi',          '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '95 days'),
  (21, 'ibrahim.cherkaoui@aui.ma',    'Ibrahim',        'Cherkaoui',    'Ibrahim Cherkaoui',     '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '90 days'),
  (22, 'nadia.benhassine@aui.ma',     'Nadia',          'Benhassine',   'Nadia Benhassine',      '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '88 days'),
  (23, 'tarik.elouali@aui.ma',        'Tarik',          'El Ouali',     'Tarik El Ouali',        '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '85 days'),
  (24, 'hind.berrada@aui.ma',         'Hind',           'Berrada',      'Hind Berrada',          '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '82 days'),
  (25, 'younes.amrani@aui.ma',        'Younes',         'Amrani',       'Younes Amrani',         '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '80 days'),
  (26, 'iman.elfassi@aui.ma',         'Iman',           'El Fassi',     'Iman El Fassi',         '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '75 days'),
  (27, 'bilal.mansouri@aui.ma',       'Bilal',          'Mansouri',     'Bilal Mansouri',        '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '70 days'),
  (28, 'rania.benkirane@aui.ma',      'Rania',          'Benkirane',    'Rania Benkirane',       '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '65 days'),
  (29, 'anas.laroui@aui.ma',          'Anas',           'Laroui',       'Anas Laroui',           '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '60 days'),
  (30, 'sana.belkhadir@aui.ma',       'Sana',           'Belkhadir',    'Sana Belkhadir',        '$2b$12$7Wkg.5n/T9ey2eTv38Q83u1ItHR2gm3jnjGGttvWm216/7vgfQuPC', FALSE, NOW() - INTERVAL '55 days');

INSERT INTO club (club_id, owner_id, name, description, created_at, main_color, status, email, icon_name)
VALUES
  (1,  2,  'Debate Club',           'Sharpen your argumentation, public speaking, and critical thinking through weekly drills and competitions.',   NOW() - INTERVAL '150 days', 'BLUE',   'active', 'debate@aui.ma',          'KNOWLEDGE'),
  (2,  3,  'Robotics Club',         'Build, program, and compete with robots. From Arduino basics to autonomous systems and computer vision.',       NOW() - INTERVAL '148 days', 'CYAN',   'active', 'robotics@aui.ma',        'AI_SPARKLES'),
  (3,  4,  'Coding Club',           'Collaborative coding, hackathons, open-source contributions, and project showcases for all skill levels.',      NOW() - INTERVAL '145 days', 'GREEN',  'active', 'coding@aui.ma',          'CODE_TERMINAL'),
  (4,  5,  'Music Club',            'Rehearsals, songwriting sessions, and campus performances spanning all genres and instruments.',                NOW() - INTERVAL '140 days', 'ROSE',   'active', 'music@aui.ma',           'MUSIC_NOTE'),
  (5,  6,  'Sports Club',           'Competitive and recreational sports including football, basketball, and athletics for all levels.',             NOW() - INTERVAL '138 days', 'TEAL',   'active', 'sports@aui.ma',          'FOOTBALL'),
  (6,  1,  'Theater Club',          'Stage productions, improv workshops, script writing, and performing arts for aspiring actors and directors.',   NOW() - INTERVAL '135 days', 'AMBER',  'active', 'theater@aui.ma',         'THEATER_MASK'),
  (7,  17, 'Photography Club',      'Explore composition, lighting, and storytelling through weekly shoots, critiques, and exhibitions.',           NOW() - INTERVAL '120 days', 'SLATE',  'active', 'photography@aui.ma',     'CAMERA_HD'),
  (8,  18, 'Chess Club',            'Casual games, tournaments, and strategy workshops for beginners and seasoned players alike.',                   NOW() - INTERVAL '118 days', 'INDIGO', 'active', 'chess@aui.ma',           'CHESS'),
  (9,  19, 'Environmental Club',    'Sustainability campaigns, campus clean-ups, tree planting, and climate awareness initiatives.',                 NOW() - INTERVAL '115 days', 'GREEN',  'active', 'environment@aui.ma',     'LEAF'),
  (10, 20, 'Film & Cinema Club',    'Film screenings, director analyses, short film production, and script development for cinema lovers.',          NOW() - INTERVAL '110 days', 'PURPLE', 'active', 'cinema@aui.ma',          'FILM'),
  (11, 21, 'Entrepreneurship Club', 'Pitch competitions, startup workshops, mentorship sessions, and networking for future founders.',               NOW() - INTERVAL '108 days', 'AMBER',  'active', 'entrepreneurship@aui.ma', 'BRIEFCASE'),
  (12, 22, 'Swimming Club',         'Competitive swim training, water polo, and open water preparation for all skill levels.',                       NOW() - INTERVAL '105 days', 'CYAN',   'active', 'swimming@aui.ma',        'SWIMMING'),
  (13, 23, 'Volleyball Club',       'Indoor and beach volleyball training, inter-university matches, and friendly tournaments.',                     NOW() - INTERVAL '100 days', 'ORANGE', 'active', 'volleyball@aui.ma',      'VOLLEYBALL'),
  (14, 24, 'Academic Excellence',   'Study groups, exam prep, research mentoring, and academic competitions across all disciplines.',                NOW() - INTERVAL '98 days',  'BLUE',   'active', 'academic@aui.ma',        'MORTARBOARD'),
  (15, 25, 'Gaming Club',           'Competitive gaming, esports tournaments, speedrunning, and casual game nights for all genres.',                 NOW() - INTERVAL '95 days',  'PURPLE', 'active', 'gaming@aui.ma',          'GAME_CONTROLLER'),
  (16, 26, 'Book Club',             'Monthly reads, literary discussions, author spotlights, and creative writing workshops.',                       NOW() - INTERVAL '90 days',  'AMBER',  'active', 'bookclub@aui.ma',        'BOOK_OPEN'),
  (17, 27, 'Cooking Club',          'Hands-on cooking sessions, international cuisine nights, bake-offs, and nutrition workshops.',                  NOW() - INTERVAL '85 days',  'RED',    'active', 'cooking@aui.ma',         'COOKBOOK'),
  (18, 28, 'Art Club',              'Painting, sketching, digital art, sculpture, and collaborative murals open to all creative souls.',             NOW() - INTERVAL '80 days',  'PINK',   'active', 'art@aui.ma',             'PAINT_BOARD'),
  (19, 29, 'Science Club',          'Experiments, lab tours, science communication, and participation in regional science fairs.',                   NOW() - INTERVAL '75 days',  'TEAL',   'active', 'science@aui.ma',         'TEST_TUBE'),
  (20, 30, 'Cycling Club',          'Group rides, trail exploration, urban cycling advocacy, and bike maintenance workshops.',                       NOW() - INTERVAL '70 days',  'GREEN',  'active', 'cycling@aui.ma',         'BICYCLE');

-- Memberships (no duplicate user+club pairs)
INSERT INTO membership (user_id, club_id, joined_at, membership_status, membership_role) VALUES
  -- Club 1 (Debate) — board: 3,12
  (3,  1, NOW() - INTERVAL '148 days', 'active', 'board_member'),
  (12, 1, NOW() - INTERVAL '140 days', 'active', 'board_member'),
  (4,  1, NOW() - INTERVAL '135 days', 'active', 'member'),
  (7,  1, NOW() - INTERVAL '130 days', 'active', 'member'),
  (10, 1, NOW() - INTERVAL '125 days', 'active', 'member'),
  (14, 1, NOW() - INTERVAL '120 days', 'active', 'member'),
  (17, 1, NOW() - INTERVAL '115 days', 'active', 'member'),
  (24, 1, NOW() - INTERVAL '80 days',  'active', 'member'),
  (29, 1, NOW() - INTERVAL '50 days',  'active', 'member'),
  -- Club 2 (Robotics) — board: 2,13
  (2,  2, NOW() - INTERVAL '146 days', 'active', 'board_member'),
  (13, 2, NOW() - INTERVAL '138 days', 'active', 'board_member'),
  (5,  2, NOW() - INTERVAL '130 days', 'active', 'member'),
  (8,  2, NOW() - INTERVAL '120 days', 'active', 'member'),
  (19, 2, NOW() - INTERVAL '90 days',  'active', 'member'),
  (25, 2, NOW() - INTERVAL '70 days',  'active', 'member'),
  -- Club 3 (Coding) — board: 6,9
  (6,  3, NOW() - INTERVAL '143 days', 'active', 'board_member'),
  (9,  3, NOW() - INTERVAL '138 days', 'active', 'board_member'),
  (13, 3, NOW() - INTERVAL '125 days', 'active', 'member'),
  (14, 3, NOW() - INTERVAL '118 days', 'active', 'member'),
  (18, 3, NOW() - INTERVAL '95 days',  'active', 'member'),
  (21, 3, NOW() - INTERVAL '80 days',  'active', 'member'),
  (27, 3, NOW() - INTERVAL '60 days',  'active', 'member'),
  -- Club 4 (Music) — board: 8,15
  (8,  4, NOW() - INTERVAL '138 days', 'active', 'board_member'),
  (15, 4, NOW() - INTERVAL '130 days', 'active', 'board_member'),
  (3,  4, NOW() - INTERVAL '125 days', 'active', 'member'),
  (10, 4, NOW() - INTERVAL '118 days', 'active', 'member'),
  (16, 4, NOW() - INTERVAL '110 days', 'active', 'member'),
  (20, 4, NOW() - INTERVAL '90 days',  'active', 'member'),
  (23, 4, NOW() - INTERVAL '75 days',  'active', 'member'),
  -- Club 5 (Sports) — board: 11,22
  (11, 5, NOW() - INTERVAL '136 days', 'active', 'board_member'),
  (22, 5, NOW() - INTERVAL '85 days',  'active', 'board_member'),
  (9,  5, NOW() - INTERVAL '128 days', 'active', 'member'),
  (15, 5, NOW() - INTERVAL '110 days', 'active', 'member'),
  (16, 5, NOW() - INTERVAL '100 days', 'active', 'member'),
  (26, 5, NOW() - INTERVAL '70 days',  'active', 'member'),
  (30, 5, NOW() - INTERVAL '50 days',  'active', 'member'),
  -- Club 6 (Theater) — board: 9,16
  (9,  6, NOW() - INTERVAL '133 days', 'active', 'board_member'),
  (16, 6, NOW() - INTERVAL '125 days', 'active', 'board_member'),
  (7,  6, NOW() - INTERVAL '120 days', 'active', 'member'),
  (10, 6, NOW() - INTERVAL '115 days', 'active', 'member'),
  (14, 6, NOW() - INTERVAL '105 days', 'active', 'member'),
  (23, 6, NOW() - INTERVAL '72 days',  'active', 'member'),
  (28, 6, NOW() - INTERVAL '60 days',  'active', 'member'),
  -- Club 7 (Photography) — board: 6,20
  (6,  7, NOW() - INTERVAL '118 days', 'active', 'board_member'),
  (20, 7, NOW() - INTERVAL '110 days', 'active', 'board_member'),
  (1,  7, NOW() - INTERVAL '105 days', 'active', 'member'),
  (14, 7, NOW() - INTERVAL '98 days',  'active', 'member'),
  (24, 7, NOW() - INTERVAL '78 days',  'active', 'member'),
  (28, 7, NOW() - INTERVAL '55 days',  'active', 'member'),
  -- Club 8 (Chess) — board: 7,12
  (7,  8, NOW() - INTERVAL '116 days', 'active', 'board_member'),
  (12, 8, NOW() - INTERVAL '108 days', 'active', 'board_member'),
  (4,  8, NOW() - INTERVAL '100 days', 'active', 'member'),
  (17, 8, NOW() - INTERVAL '90 days',  'active', 'member'),
  (25, 8, NOW() - INTERVAL '75 days',  'active', 'member'),
  (29, 8, NOW() - INTERVAL '48 days',  'active', 'member'),
  -- Club 9 (Environmental) — board: 11,26
  (11, 9, NOW() - INTERVAL '113 days', 'active', 'board_member'),
  (26, 9, NOW() - INTERVAL '72 days',  'active', 'board_member'),
  (14, 9, NOW() - INTERVAL '105 days', 'active', 'member'),
  (20, 9, NOW() - INTERVAL '92 days',  'active', 'member'),
  (27, 9, NOW() - INTERVAL '62 days',  'active', 'member'),
  (30, 9, NOW() - INTERVAL '48 days',  'active', 'member'),
  -- Club 10 (Film) — board: 6,21
  (6,  10, NOW() - INTERVAL '108 days', 'active', 'board_member'),
  (21, 10, NOW() - INTERVAL '100 days', 'active', 'board_member'),
  (9,  10, NOW() - INTERVAL '95 days',  'active', 'member'),
  (16, 10, NOW() - INTERVAL '88 days',  'active', 'member'),
  (23, 10, NOW() - INTERVAL '70 days',  'active', 'member'),
  (28, 10, NOW() - INTERVAL '55 days',  'active', 'member'),
  -- Club 11 (Entrepreneurship) — board: 2,13
  (2,  11, NOW() - INTERVAL '106 days', 'active', 'board_member'),
  (13, 11, NOW() - INTERVAL '98 days',  'active', 'board_member'),
  (4,  11, NOW() - INTERVAL '90 days',  'active', 'member'),
  (17, 11, NOW() - INTERVAL '82 days',  'active', 'member'),
  (22, 11, NOW() - INTERVAL '75 days',  'active', 'member'),
  (24, 11, NOW() - INTERVAL '65 days',  'active', 'member'),
  (29, 11, NOW() - INTERVAL '45 days',  'active', 'member'),
  -- Club 12 (Swimming) — board: 5,19
  (5,  12, NOW() - INTERVAL '103 days', 'active', 'board_member'),
  (19, 12, NOW() - INTERVAL '95 days',  'active', 'board_member'),
  (15, 12, NOW() - INTERVAL '88 days',  'active', 'member'),
  (23, 12, NOW() - INTERVAL '78 days',  'active', 'member'),
  (25, 12, NOW() - INTERVAL '65 days',  'active', 'member'),
  (30, 12, NOW() - INTERVAL '50 days',  'active', 'member'),
  -- Club 13 (Volleyball) — board: 8,20
  (8,  13, NOW() - INTERVAL '98 days',  'active', 'board_member'),
  (20, 13, NOW() - INTERVAL '90 days',  'active', 'board_member'),
  (11, 13, NOW() - INTERVAL '85 days',  'active', 'member'),
  (16, 13, NOW() - INTERVAL '78 days',  'active', 'member'),
  (26, 13, NOW() - INTERVAL '65 days',  'active', 'member'),
  (29, 13, NOW() - INTERVAL '42 days',  'active', 'member'),
  -- Club 14 (Academic Excellence) — board: 3,7
  (3,  14, NOW() - INTERVAL '96 days',  'active', 'board_member'),
  (7,  14, NOW() - INTERVAL '88 days',  'active', 'board_member'),
  (10, 14, NOW() - INTERVAL '82 days',  'active', 'member'),
  (12, 14, NOW() - INTERVAL '75 days',  'active', 'member'),
  (18, 14, NOW() - INTERVAL '62 days',  'active', 'member'),
  (27, 14, NOW() - INTERVAL '52 days',  'active', 'member'),
  -- Club 15 (Gaming) — board: 4,21
  (4,  15, NOW() - INTERVAL '93 days',  'active', 'board_member'),
  (21, 15, NOW() - INTERVAL '85 days',  'active', 'board_member'),
  (6,  15, NOW() - INTERVAL '78 days',  'active', 'member'),
  (13, 15, NOW() - INTERVAL '70 days',  'active', 'member'),
  (17, 15, NOW() - INTERVAL '60 days',  'active', 'member'),
  (28, 15, NOW() - INTERVAL '45 days',  'active', 'member'),
  (30, 15, NOW() - INTERVAL '35 days',  'active', 'member'),
  -- Club 16 (Book Club) — board: 10,22
  (10, 16, NOW() - INTERVAL '88 days',  'active', 'board_member'),
  (22, 16, NOW() - INTERVAL '80 days',  'active', 'board_member'),
  (3,  16, NOW() - INTERVAL '75 days',  'active', 'member'),
  (18, 16, NOW() - INTERVAL '65 days',  'active', 'member'),
  (24, 16, NOW() - INTERVAL '58 days',  'active', 'member'),
  (27, 16, NOW() - INTERVAL '48 days',  'active', 'member'),
  (29, 16, NOW() - INTERVAL '38 days',  'active', 'member'),
  -- Club 17 (Cooking) — board: 5,15
  (5,  17, NOW() - INTERVAL '83 days',  'active', 'board_member'),
  (15, 17, NOW() - INTERVAL '75 days',  'active', 'board_member'),
  (11, 17, NOW() - INTERVAL '68 days',  'active', 'member'),
  (20, 17, NOW() - INTERVAL '58 days',  'active', 'member'),
  (23, 17, NOW() - INTERVAL '48 days',  'active', 'member'),
  (28, 17, NOW() - INTERVAL '38 days',  'active', 'member'),
  -- Club 18 (Art) — board: 6,14
  (6,  18, NOW() - INTERVAL '78 days',  'active', 'board_member'),
  (14, 18, NOW() - INTERVAL '70 days',  'active', 'board_member'),
  (9,  18, NOW() - INTERVAL '65 days',  'active', 'member'),
  (19, 18, NOW() - INTERVAL '58 days',  'active', 'member'),
  (21, 18, NOW() - INTERVAL '48 days',  'active', 'member'),
  (26, 18, NOW() - INTERVAL '38 days',  'active', 'member'),
  (30, 18, NOW() - INTERVAL '28 days',  'active', 'member'),
  -- Club 19 (Science) — board: 8,25
  (8,  19, NOW() - INTERVAL '73 days',  'active', 'board_member'),
  (25, 19, NOW() - INTERVAL '65 days',  'active', 'board_member'),
  (2,  19, NOW() - INTERVAL '60 days',  'active', 'member'),
  (13, 19, NOW() - INTERVAL '52 days',  'active', 'member'),
  (22, 19, NOW() - INTERVAL '44 days',  'active', 'member'),
  (27, 19, NOW() - INTERVAL '35 days',  'active', 'member'),
  (30, 19, NOW() - INTERVAL '25 days',  'active', 'member'),
  -- Club 20 (Cycling) — board: 5,17
  (5,  20, NOW() - INTERVAL '68 days',  'active', 'board_member'),
  (17, 20, NOW() - INTERVAL '60 days',  'active', 'board_member'),
  (11, 20, NOW() - INTERVAL '55 days',  'active', 'member'),
  (20, 20, NOW() - INTERVAL '45 days',  'active', 'member'),
  (23, 20, NOW() - INTERVAL '38 days',  'active', 'member'),
  (26, 20, NOW() - INTERVAL '28 days',  'active', 'member');

-- Posts (3 per club)
INSERT INTO post (club_id, user_id, title, content, created_at, updated_at, is_deleted)
VALUES
  (1,  2,  'Welcome to Debate Club!',          'Kick-off meeting this Saturday at 2 PM in room 204. We will cover the semester calendar and warm up with a short impromptu round.',          NOW() - INTERVAL '148 days', NULL, FALSE),
  (1,  3,  'Topic this week: AI regulation',   'Debate whether AI-generated content should be regulated. Prepare a 2-minute opening statement. Pro/con assignments posted in the group chat.', NOW() - INTERVAL '90 days', NULL, FALSE),
  (1,  12, 'Regional finals: we qualified!',   'Finals are in three weeks. Mandatory practice Tuesday and Thursday at 5 PM. All participants must confirm attendance by Sunday.',              NOW() - INTERVAL '45 days', NULL, FALSE),
  (1,  7,  'Guest speaker: Prof. Benali',       'Professor Benali from the law faculty will discuss argumentation in legal contexts. Open to everyone. Room 101, Thursday 6 PM.',             NOW() - INTERVAL '20 days', NULL, FALSE),
  (2,  3,  'Semester kickoff: line-follower',   'We start with an Arduino Mega line-follower robot. Parts list in the shared drive. First session is hands-on with no experience required.',  NOW() - INTERVAL '146 days', NULL, FALSE),
  (2,  2,  'Sensors arrived',                   'Ultrasonic sensors and servo motors are in. Pick yours up from the lab cabinet. Label with your name before next session.',                   NOW() - INTERVAL '100 days', NULL, FALSE),
  (2,  13, 'Workshop: intro to computer vision','OpenCV and object detection on Raspberry Pi. Bring a laptop with Python 3.11 installed. Wednesday 5 PM, lab 3.',                             NOW() - INTERVAL '60 days', NULL, FALSE),
  (2,  8,  'NatRobot 2026 competition',         'We are entering the inter-university robotics competition in June. Registration closes April 20. Talk to the board to join the team.',        NOW() - INTERVAL '30 days', NULL, FALSE),
  (3,  4,  'Hackathon team sign-ups',           'Inter-university hackathon in 5 weeks. Teams of 4. Theme: sustainable tech. Sign up on the board by Wednesday.',                             NOW() - INTERVAL '143 days', NULL, FALSE),
  (3,  6,  'Code review Fridays',               'Every Friday at 4 PM. Bring a recent snippet or project. All languages welcome. Constructive feedback, no gatekeeping.',                    NOW() - INTERVAL '95 days', NULL, FALSE),
  (3,  9,  'Project: AUI course planner',       'Building a full-stack course planner for students. Stack: Next.js + PostgreSQL. Message Malik if you want to contribute.',                   NOW() - INTERVAL '55 days', NULL, FALSE),
  (3,  13, 'Docker workshop recap',             'Slides and recording posted in the shared folder. Next week: Docker Compose and networking. Attendance has been great, keep it up.',          NOW() - INTERVAL '22 days', NULL, FALSE),
  (4,  5,  'Spring rehearsal schedule',         'Rehearsals every Monday and Wednesday at 7 PM in the music room. First campus performance is March 30. All instruments welcome.',            NOW() - INTERVAL '138 days', NULL, FALSE),
  (4,  8,  'Songwriting challenge',             'Write an original piece or arrangement by month end. Best submission gets performed at the end-of-semester showcase. Solo or group entries.', NOW() - INTERVAL '88 days', NULL, FALSE),
  (4,  15, 'End-of-semester concert confirmed', 'We perform in the main hall on May 25 at 7 PM. Each member gets 3 tickets. Invite your family!',                                             NOW() - INTERVAL '40 days', NULL, FALSE),
  (5,  6,  'Training schedule live',            'Football: Tue/Thu/Sat 6 AM on the main field. Basketball: Tue/Thu 5 PM in the gym. Full schedule posted on the notice board.',              NOW() - INTERVAL '136 days', NULL, FALSE),
  (5,  11, 'Hosting the regional tournament',   'We are hosting the regional tournament on April 12. Volunteers needed for logistics and refereeing. Sign up by April 5.',                    NOW() - INTERVAL '80 days', NULL, FALSE),
  (5,  22, 'Nutrition workshop recap',          'Thank you Dr. Alami for the sports nutrition session. Summary notes in the group chat. Next: sleep optimization with a sports psychologist.', NOW() - INTERVAL '42 days', NULL, FALSE),
  (6,  1,  'Auditions open: The Glass Menagerie','Auditions this Friday and Saturday 3–6 PM. Prepare a one-minute monologue. All experience levels welcome.',                                 NOW() - INTERVAL '133 days', NULL, FALSE),
  (6,  9,  'Improv workshop every Thursday',    'No prep needed. Games, scenes, and exercises to sharpen your instincts. Thursdays 5:30 PM, room 118. Drop in anytime.',                     NOW() - INTERVAL '85 days', NULL, FALSE),
  (6,  16, 'Volunteers for set and costumes',   'We need 6 volunteers for costumes and 4 for set painting. No experience required. Message Zainab to sign up before Saturday.',               NOW() - INTERVAL '45 days', NULL, FALSE),
  (7,  17, 'First shoot: campus golden hour',   'Meet at the main entrance Saturday at 7 AM. Bring your camera or phone. We will go over composition rules on-site.',                         NOW() - INTERVAL '118 days', NULL, FALSE),
  (7,  6,  'Monthly contest: "Motion"',         'Submit your best "Motion" photo by end of month. One entry per member, JPEG format, minimum 3 MB. Winner at next meeting.',                  NOW() - INTERVAL '65 days', NULL, FALSE),
  (7,  20, 'Lightroom editing workshop',        'Non-destructive editing, color grading, and export settings. Bring a laptop. Saturday 2 PM, room 205. Lightroom trial link in sidebar.',     NOW() - INTERVAL '35 days', NULL, FALSE),
  (8,  18, 'Weekly Swiss tournament',           'Every Wednesday at 6 PM. Register by Tuesday midnight. Ratings tracked across the semester. ELO board updated after each round.',            NOW() - INTERVAL '116 days', NULL, FALSE),
  (8,  7,  'Beginner crash course',             'Three sessions covering openings, middle game tactics, and endgames. Starts next Saturday. Free for all club members.',                       NOW() - INTERVAL '70 days', NULL, FALSE),
  (8,  12, 'National student championship',     'We are sending three players to the nationals in Rabat on May 10. Selection game this Friday at 5 PM. Top 3 go.',                            NOW() - INTERVAL '38 days', NULL, FALSE),
  (9,  19, 'Campus clean-up Saturday',          'Join us 9–11 AM for a campus-wide clean-up. Gloves and bags provided. Sign up so we can plan the teams in advance.',                         NOW() - INTERVAL '113 days', NULL, FALSE),
  (9,  11, '47 trees planted this semester!',   'Thank you to everyone who showed up. Photos on the club page. Our next goal is 100 trees by end of academic year.',                          NOW() - INTERVAL '75 days', NULL, FALSE),
  (9,  26, 'Panel: climate action on campus',   'Panel discussion with faculty on sustainability steps for AUI. Open to all. Wednesday 4 PM in the amphitheater.',                            NOW() - INTERVAL '40 days', NULL, FALSE),
  (10, 20, 'Screening: Parasite + discussion',  'Friday we screen Bong Joon-ho''s "Parasite" then discuss class dynamics in cinema. Room 210, 8 PM. Free entry.',                            NOW() - INTERVAL '108 days', NULL, FALSE),
  (10, 6,  'Short film: open call',             'Producing a 10-minute short film in March. Looking for director, DP, actors, and sound. No experience required, just passion.',              NOW() - INTERVAL '68 days', NULL, FALSE),
  (10, 21, 'Script workshop Tuesdays',          'Bring ideas or works-in-progress for group feedback. All genres welcome. Tuesday 6 PM, library seminar room.',                               NOW() - INTERVAL '35 days', NULL, FALSE),
  (11, 21, 'Pitch competition: sign up',        'Our annual internal pitch competition is in 6 weeks. Teams of 2–4. Grand prize: 5000 MAD seed grant. Mentorship available.',                 NOW() - INTERVAL '106 days', NULL, FALSE),
  (11, 2,  'Workshop: Business Model Canvas',   'We covered the BMC with 8 teams. Recording and templates in the shared folder. Next session: financial projections and unit economics.',      NOW() - INTERVAL '65 days', NULL, FALSE),
  (11, 4,  'Alumni talk: founder journey',      'AUI alum Yassine Bensouda, founder of TechMa, joins remotely next Monday at 7 PM. Submit questions in advance on the form.',                NOW() - INTERVAL '12 days', NULL, FALSE),
  (12, 22, 'Spring pool schedule',              'Morning: Mon/Wed/Fri 6:30 AM. Evening: Tue/Thu 6 PM. New members complete a 200 m time trial in week one.',                                 NOW() - INTERVAL '103 days', NULL, FALSE),
  (12, 5,  'Water polo team forming',           'Starting a water polo team. Open positions for goalkeepers and field players. First practice next Saturday at 7 AM.',                        NOW() - INTERVAL '60 days', NULL, FALSE),
  (12, 19, 'Regional swim meet results',        '3 gold, 2 silver, 1 bronze. Full results on the club page. Congratulations to all competitors!',                                             NOW() - INTERVAL '28 days', NULL, FALSE),
  (13, 23, 'Training schedule: spring',         'Tue/Thu at 5 PM on court B, Saturday 9 AM for match simulation. Beach volleyball Sundays at 8 AM weather permitting.',                      NOW() - INTERVAL '98 days', NULL, FALSE),
  (13, 8,  'Mixed 6-team tournament Sunday',    'Hosting a mixed tournament this Sunday. Spectators welcome. Come support the team and enjoy some great volleyball.',                          NOW() - INTERVAL '55 days', NULL, FALSE),
  (13, 20, 'New equipment in',                  'Two volleyballs, a cart, and knee pads for 12 players. Stored in the sports room — ask any board member for access.',                        NOW() - INTERVAL '22 days', NULL, FALSE),
  (14, 24, 'Study group sign-ups',              'Groups for CS, Math, and Physics midterms. Groups of 5–6 students. Sign up by end of week, room assignments Monday.',                        NOW() - INTERVAL '96 days', NULL, FALSE),
  (14, 3,  'Research mentoring available',      'Two faculty mentors for students starting research projects. Office hours: Tuesday 2–4 PM, Friday 10–12. Book via email.',                   NOW() - INTERVAL '58 days', NULL, FALSE),
  (14, 7,  'Academic competition: join us',     'National multi-discipline student competition in April. We are sending a team. Qualifying assessment this Friday at 5 PM.',                  NOW() - INTERVAL '30 days', NULL, FALSE),
  (15, 25, 'Valorant tournament bracket live',  'Season 1 bracket is up in Discord. Matches run Sat/Sun for 3 weekends. Check your schedule and confirm your slot.',                          NOW() - INTERVAL '93 days', NULL, FALSE),
  (15, 4,  'Board game night Friday',           'Catan, Codenames, and Azul this Friday. No screens, just vibes. Common room at 7 PM. Bring snacks.',                                         NOW() - INTERVAL '55 days', NULL, FALSE),
  (15, 21, 'Speedrunning leaderboard launched', 'Tracking times for Celeste, Hollow Knight, and Mario Odyssey. Submit your times. Any% welcome. Leaderboard link in Discord.',               NOW() - INTERVAL '25 days', NULL, FALSE),
  (16, 26, 'March read: The Alchemist',         'This month we read Paulo Coelho''s "The Alchemist." Discussion on March 28 at 5 PM, room 112. Questions posted beforehand.',                NOW() - INTERVAL '88 days', NULL, FALSE),
  (16, 10, 'Creative writing night',            'Bring a short piece — poem, flash fiction, or essay — to read aloud. Monthly Fridays at 6 PM. Supportive and judgment-free.',               NOW() - INTERVAL '52 days', NULL, FALSE),
  (16, 22, 'Author spotlight: Ben Jelloun',     'Next session features Tahar Ben Jelloun. Read at least one short story before Thursday. Summary available on request.',                      NOW() - INTERVAL '18 days', NULL, FALSE),
  (17, 27, 'Session 1: Moroccan tagine',        'First session this Saturday at 11 AM. We are making lamb tagine. Ingredients list posted. Bring an apron and appetite!',                    NOW() - INTERVAL '83 days', NULL, FALSE),
  (17, 5,  'International cuisine night',       'Each member brings a dish from a different country. 14 countries, 14 dishes. Friday 7 PM, student lounge. Sign up for your spot.',          NOW() - INTERVAL '48 days', NULL, FALSE),
  (17, 15, 'Bake-off: chocolate theme',         'Each team of 2 presents one chocolate creation. Judged on taste, presentation, and creativity. April 10 — come hungry.',                    NOW() - INTERVAL '20 days', NULL, FALSE),
  (18, 28, 'Open studio every Saturday',        'Art room open Saturday 2–6 PM. Materials provided. Work on personal projects or collaborate. All mediums welcome.',                          NOW() - INTERVAL '78 days', NULL, FALSE),
  (18, 6,  'Campus mural project',              'Designing a mural for the east wall of the student center. Concept proposals due March 20. Final design voted on by all members.',           NOW() - INTERVAL '45 days', NULL, FALSE),
  (18, 14, 'Annual exhibition: May 20',         'Every member submits 1–2 pieces. All media accepted. Setup begins May 18 — help needed with hanging and lighting.',                          NOW() - INTERVAL '15 days', NULL, FALSE),
  (19, 29, 'Lab tour: chemistry department',    'Visiting the chem lab Thursday at 3 PM. Limited spots — first come first served. Meet at the science building entrance.',                    NOW() - INTERVAL '73 days', NULL, FALSE),
  (19, 8,  'Science fair team forming',         'Entering the national science fair in May. Teams of 3 with a project idea. Internal submission deadline: April 1.',                          NOW() - INTERVAL '40 days', NULL, FALSE),
  (19, 25, 'Talk: quantum computing overview',  'PhD student Amine Rifi gives a 45-minute intro to quantum computing. All welcome. Thursday 5 PM, amphitheater.',                             NOW() - INTERVAL '18 days', NULL, FALSE),
  (20, 30, 'Sunday group ride: 7 AM',           'Every Sunday from the main gate. This week: Ifrane forest loop (~25 km). Helmets mandatory. Bring water.',                                  NOW() - INTERVAL '68 days', NULL, FALSE),
  (20, 5,  'Bike maintenance workshop',         'Fix a flat, adjust brakes, tune your drivetrain. Saturday 10 AM, parking lot B. Bring your bike if you have one.',                          NOW() - INTERVAL '40 days', NULL, FALSE),
  (20, 17, 'Trail ride: Azrou forest April 26', '40 km trail to Azrou forest. Intermediate level. RSVP by April 20 so we can arrange transport.',                                            NOW() - INTERVAL '15 days', NULL, FALSE);

-- Join requests
INSERT INTO joinrequest (initiator_user_id, target_club_id, reviewer_user_id, request_type, status, message, created_at, reviewed_at)
VALUES
  -- Pending
  (2,  5,  NULL, 'join', 'pending', 'Want to stay active and improve my fitness outside of class.',               NOW() - INTERVAL '3 days',   NULL),
  (2,  3,  NULL, 'join', 'pending', 'I have been working on side projects in Next.js and PostgreSQL and would love to contribute.',  NOW() - INTERVAL '1 day',    NULL),
  (5,  1,  NULL, 'join', 'pending', 'Critical thinking and argumentation are skills I really want to develop.',   NOW() - INTERVAL '1 day',    NULL),
  (7,  10, NULL, 'join', 'pending', 'Cinema enthusiast — I watch 3 films a week and want to discuss them.',      NOW() - INTERVAL '4 days',   NULL),
  (10, 2,  NULL, 'join', 'pending', 'Fascinated by robotics and IoT. Have some Arduino experience.',              NOW() - INTERVAL '7 days',   NULL),
  (14, 15, NULL, 'join', 'pending', 'Competitive gamer, play Valorant and CS2 at a decent rank.',                 NOW() - INTERVAL '2 days',   NULL),
  (17, 4,  NULL, 'join', 'pending', 'Play guitar and piano. Looking for people to jam with.',                     NOW() - INTERVAL '5 days',   NULL),
  (18, 8,  NULL, 'join', 'pending', 'Chess player since I was 8. Want to get back into competitive play.',        NOW() - INTERVAL '6 days',   NULL),
  (19, 16, NULL, 'join', 'pending', 'Avid reader — love sci-fi and literary fiction.',                            NOW() - INTERVAL '3 days',   NULL),
  (21, 1,  NULL, 'join', 'pending', 'I have debate experience from high school MUN.',                             NOW() - INTERVAL '1 day',    NULL),
  (22, 3,  NULL, 'join', 'pending', 'Full-stack dev — React and Node. Want to contribute to real projects.',      NOW() - INTERVAL '4 days',   NULL),
  (24, 20, NULL, 'join', 'pending', 'Cyclist, ride 50 km per week. Very interested in group rides.',              NOW() - INTERVAL '2 days',   NULL),
  (25, 6,  NULL, 'join', 'pending', 'Did theater in high school, want to get back on stage.',                     NOW() - INTERVAL '8 days',   NULL),
  (27, 4,  NULL, 'join', 'pending', 'Drummer with 5 years of experience, looking for a band environment.',        NOW() - INTERVAL '1 day',    NULL),
  (1,  9,  NULL, 'join', 'pending', 'Sustainability is something I care deeply about.',                           NOW() - INTERVAL '3 days',   NULL),
  (15, 10, NULL, 'join', 'pending', 'Huge film fan, want to discuss and help produce short films.',                NOW() - INTERVAL '5 days',   NULL),
  (16, 11, NULL, 'join', 'pending', 'Working on a startup idea and looking for community and feedback.',           NOW() - INTERVAL '2 days',   NULL),
  (28, 12, NULL, 'join', 'pending', 'Former swimmer looking to get back in shape.',                                NOW() - INTERVAL '6 days',   NULL),
  (29, 17, NULL, 'join', 'pending', 'Love cooking Moroccan and Mediterranean cuisine.',                            NOW() - INTERVAL '4 days',   NULL),
  -- Approved (historical)
  (9,  1,  2,  'join', 'approved', 'Love debate and critical thinking. Was on my high school team.',              NOW() - INTERVAL '125 days', NOW() - INTERVAL '124 days'),
  (11, 5,  6,  'join', 'approved', 'Competitive athlete, committed to the training schedule.',                    NOW() - INTERVAL '140 days', NOW() - INTERVAL '139 days'),
  (12, 1,  2,  'join', 'approved', 'Want to improve public speaking and logical argumentation.',                  NOW() - INTERVAL '142 days', NOW() - INTERVAL '141 days'),
  (20, 4,  5,  'join', 'approved', 'Vocalist looking for a band environment.',                                    NOW() - INTERVAL '92 days',  NOW() - INTERVAL '91 days'),
  (26, 5,  6,  'join', 'approved', 'Former semi-pro basketball player.',                                          NOW() - INTERVAL '72 days',  NOW() - INTERVAL '71 days'),
  (19, 12, 22, 'join', 'approved', 'Competitive swimmer, trained for 6 years.',                                   NOW() - INTERVAL '97 days',  NOW() - INTERVAL '96 days'),
  (14, 9,  19, 'join', 'approved', 'Really care about environmental sustainability.',                             NOW() - INTERVAL '107 days', NOW() - INTERVAL '106 days'),
  (6,  3,  4,  'join', 'approved', 'Strong electronics and coding background.',                                    NOW() - INTERVAL '145 days', NOW() - INTERVAL '144 days'),
  -- Rejected (historical)
  (2,  17, 27, 'join', 'rejected', 'Apply again after our next open session.',                                    NOW() - INTERVAL '80 days',  NOW() - INTERVAL '79 days'),
  (13, 7,  17, 'join', 'rejected', 'Great interest but slots are full. Please reapply next semester.',            NOW() - INTERVAL '110 days', NOW() - INTERVAL '109 days'),
  (15, 2,  3,  'join', 'rejected', 'We need hands-on experience. Try our intro workshop first.',                  NOW() - INTERVAL '118 days', NOW() - INTERVAL '117 days'),
  (16, 14, 24, 'join', 'rejected', 'At capacity this term. Priority given to upper-year students.',               NOW() - INTERVAL '90 days',  NOW() - INTERVAL '89 days'),
  (23, 19, 29, 'join', 'rejected', 'Biology background preferred. Consider applying in spring.',                   NOW() - INTERVAL '70 days',  NOW() - INTERVAL '69 days');

-- Club creation requests
INSERT INTO club_creation_request (request_id, initiator_user_id, name, description, main_color, icon_name, email, status, reviewer_message, created_at, reviewed_at)
VALUES
  (1, 8,  'Art & Design Club',   'Workshops on painting, illustration, digital art, and mixed media.',         'PINK',   'PAINT_BOARD',   'artdesign@aui.ma',   'pending',  NULL,                                                        NOW() - INTERVAL '30 days', NULL),
  (2, 10, 'Tennis Club',         'Weekly tennis drills, friendly matches, and court booking coordination.',    'CYAN',   'FOOTBALL',      'tennis@aui.ma',      'pending',  NULL,                                                        NOW() - INTERVAL '25 days', NULL),
  (3, 17, 'Adventure Club',      'Hiking, camping, orienteering, and outdoor survival skills.',                'YELLOW', 'ADVENTURE',     'adventure@aui.ma',   'pending',  NULL,                                                        NOW() - INTERVAL '20 days', NULL),
  (4, 14, 'Language Exchange',   'Pair up with native speakers to practice Arabic, French, English.',          'BLUE',   'KNOWLEDGE',     'langex@aui.ma',      'rejected', 'Similar initiative already runs through the language dept.', NOW() - INTERVAL '40 days', NOW() - INTERVAL '38 days'),
  (5, 19, '3D Printing Club',    'Design and print physical objects using campus Prusa printers.',             'PURPLE', 'CODE_TERMINAL', 'printing@aui.ma',    'pending',  NULL,                                                        NOW() - INTERVAL '15 days', NULL),
  (6, 22, 'Astronomy Club',      'Stargazing nights, telescope sessions, and space science discussions.',     'PURPLE', 'AI_SPARKLES',   'astronomy@aui.ma',   'pending',  NULL,                                                        NOW() - INTERVAL '10 days', NULL),
  (7, 25, 'Meditation Club',     'Guided meditation, breathwork, and mindfulness workshops.',                  'GREEN',  'LAUREL_WREATH', 'meditation@aui.ma',  'approved', NULL,                                                        NOW() - INTERVAL '50 days', NOW() - INTERVAL '48 days');

-- Advance sequences
SELECT setval(pg_get_serial_sequence('users', 'user_id'), coalesce(max(user_id), 0) + 1, false) FROM users;
SELECT setval(pg_get_serial_sequence('club', 'club_id'), coalesce(max(club_id), 0) + 1, false) FROM club;
SELECT setval(pg_get_serial_sequence('membership', 'membership_id'), coalesce(max(membership_id), 0) + 1, false) FROM membership;
SELECT setval(pg_get_serial_sequence('post', 'post_id'), coalesce(max(post_id), 0) + 1, false) FROM post;
SELECT setval(pg_get_serial_sequence('joinrequest', 'request_id'), coalesce(max(request_id), 0) + 1, false) FROM joinrequest;
SELECT setval(pg_get_serial_sequence('club_creation_request', 'request_id'), coalesce(max(request_id), 0) + 1, false) FROM club_creation_request;
